FIX instructor error when submit/edit resp
Instructors don't have grade passback, but it still tries and encounters
this error:
  Fatal error: Uncaught TypeError: stream_get_contents(): Argument #1
  ($stream) must be of type resource, bool given in
  /var/www/html/grade.php:69 Stack trace: #0
  /var/www/html/grade.php(69): stream_get_contents(false) #1
  /var/www/html/edit_response.php(83): require('/var/www/html/g...') #2
  {main} thrown in /var/www/html/grade.php on line 69

I noticed that instructors don't have 'lis_result_sourcedid' set, which
is what fails the grade passback request. So now responsemap will only
try to passback grades if that is set.